### ISSUE TITLE
vymyslet systém na ukládání projektů

### ISSUE THREAD

**Issue by kamiska-kocicka** [science-21/nevim-co-zvolit#1]
úkol

**Comment by ingSlonik** [comment]
Mě se tenhle docela líbí. Co myslíš @martin-pechanda ?

**Comment by martin-pechanda** [comment]
Jo, jenom bych tomu změnil to jméno.. ;-)

S pozdravem

Bc. Martin Pechanda
martin@pechanda.cz
+420 737 33 66 01
